output "s3_bucket_name" {
  description = "Name of the origin S3 bucket storing static website artifacts"
  value       = aws_s3_bucket.website.id
}

output "s3_bucket_arn" {
  description = "ARN of the origin S3 bucket"
  value       = aws_s3_bucket.website.arn
}

output "cloudfront_distribution_id" {
  description = "ID of the CloudFront CDN distribution (used for CI/CD cache invalidation)"
  value       = aws_cloudfront_distribution.cdn.id
}

output "cloudfront_domain_name" {
  description = "Domain name generated by CloudFront distribution"
  value       = aws_cloudfront_distribution.cdn.domain_name
}

output "website_url" {
  description = "Production URL of the website"
  value       = "https://${var.domain_name}"
}
